name: CHATS_Vendor
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+43 #Always increase the version number before running the flutter build appbundle command

environment:
  # sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  json_annotation: ^4.0.1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  dio: ^5.0.0
  intl: ^0.17.0

  build_runner: ^2.0.6
  json_serializable: ^6.6.1

  date_format: ^2.0.2
  carousel_slider: ^4.0.0
  flutter_spinkit: ^5.0.0
  # flutter_barcode_scanner: ^2.0.0

  # image_picker: ^0.8.2
  image_picker: ^0.8.0+4

  cupertino_icons: ^1.0.0
  textfield_tags: ^2.0.2
  snack: ^2.0.0
  qr_flutter: ^4.0.0
  badges: ^3.0.2
  # flutter_local_auth_invisible: ^2.2.0
  barcode_scan2: ^4.2.1
  jiffy: ^5.0.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_markdown: ^0.6.10+3
  # nfc_manager: ^3.1.1
  flutter_modular: ^5.0.3
  flutter_screenutil: ^5.5.4
  url_launcher: ^6.1.5
  flutter_password_strength: ^0.1.6
  permission_handler: ^10.2.0
  bottom_drawer: ^0.0.5
  # local_auth: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/icons/chats_vendor_app_icon_2.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/
    - images/
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/home/
    - assets/images/login/
    - assets/icons/chats_vendor_app_icon_white.png
    - assets/icons/chats_vendor_app_icon_2.png

  fonts:
    - family: Gilroy-bold
      fonts:
        - asset: fonts/Gilroy-ExtraBold.ttf
        # - asset: fonts/Gilroy-Light.ttf
    #         style: italic
    - family: Gilroy-medium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
        # - asset: fonts/Gilroy-Light.ttf
    #         style: italic
    - family: Gilroy-Regular
      fonts:
        - asset: fonts/Gilroy-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
